set(PLOG_SHARED_EXPORT PLOG_GLOBAL)
if(WIN32)
	set(PLOG_SHARED_EXPORT PLOG_EXPORT)
endif()

AddTarget(logging	shared_lib
	SOURCE_DIRECTORY
		${CMAKE_CURRENT_LIST_DIR}
	PROJECT_GROUP Foundation
	LINK_LIBRARIES
		Qt${QT_MAJOR_VERSION}::Core
		LINK_PUBLIC plog::plog
	COMPILE_DEFINITIONS
		${PLOG_SHARED_EXPORT}
)
